"""Add callback tracking fields

Revision ID: dd0aa3a42a85
Revises: 001
Create Date: 2026-01-19 14:56:20.850323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0aa3a42a85'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('last_callback_time', sa.DateTime(), nullable=True, comment='Last time a callback updated this run'))
    op.add_column('workflow_runs', sa.Column('last_event_id', sa.String(length=100), nullable=True, comment='Last EventBridge event ID processed (for idempotency)'))
    op.create_index(op.f('ix_workflow_runs_last_callback_time'), 'workflow_runs', ['last_callback_time'], unique=False)
    op.create_index(op.f('ix_workflow_runs_last_event_id'), 'workflow_runs', ['last_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_runs_last_event_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_last_callback_time'), table_name='workflow_runs')
    op.drop_column('workflow_runs', 'last_event_id')
    op.drop_column('workflow_runs', 'last_callback_time')
    # ### end Alembic commands ###