"""Add field comment to workflow_run_id on WorkflowRun table

Revision ID: ea7b7b3086d2
Revises: 1c1081db9f3d
Create Date: 2026-03-03 19:01:20.001621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea7b7b3086d2'
down_revision = '1c1081db9f3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_runs', 'workflow_run_id',
               existing_type=mysql.VARCHAR(length=36),
               comment='ID for the executed workflow run in the underlying execution system (e.g. Omics Run ID)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_runs', 'workflow_run_id',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='ID for the executed workflow run in the underlying execution system (e.g. Omics Run ID)',
               existing_nullable=True)
    # ### end Alembic commands ###