"""Add workflow_run_id to WorkflowRun table

Revision ID: 1c1081db9f3d
Revises: dd0aa3a42a85
Create Date: 2026-03-03 18:55:59.221470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1081db9f3d'
down_revision = 'dd0aa3a42a85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('workflow_run_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_workflow_runs_workflow_run_id'), 'workflow_runs', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_runs_workflow_run_id'), table_name='workflow_runs')
    op.drop_column('workflow_runs', 'workflow_run_id')
    # ### end Alembic commands ###