"""track workflows in db

Revision ID: 2a8e78b474e2
Revises: 61f86f423e51
Create Date: 2025-04-26 21:16:16.337932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a8e78b474e2'
down_revision = '61f86f423e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('processed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.drop_column('workflow_id')
        batch_op.drop_column('storage_capacity')
        batch_op.drop_column('storage_type')
        batch_op.drop_column('arn')
        batch_op.drop_column('priority')
        batch_op.drop_column('stop_time')
        batch_op.drop_column('creation_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('stop_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('priority', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('arn', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('storage_type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('storage_capacity', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('workflow_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.drop_column('error_message')
        batch_op.drop_column('external_id')
        batch_op.drop_column('processed')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
