"""Add submitted_at column

Revision ID: 31af619843e7
Revises: 65510080a98b
Create Date: 2025-05-15 17:41:49.499750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31af619843e7'
down_revision = '65510080a98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_column('submitted_at')

    # ### end Alembic commands ###
