"""add aws omics fields to workflow_runs

Revision ID: 61f86f423e51
Revises: 65510080a98b
Create Date: 2025-04-16 16:32:19.275235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '61f86f423e51'
down_revision = '65510080a98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arn', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('workflow_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('storage_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('creation_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('stop_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('storage_type', sa.String(length=50), nullable=True))
    
    # Copy data from end_time to stop_time before dropping end_time
    connection = op.get_bind()
    connection.execute(
        text('UPDATE workflow_runs SET stop_time = end_time')
    )
    
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=True))
    
    # Copy data from stop_time to end_time before dropping stop_time
    connection = op.get_bind()
    connection.execute(
        text('UPDATE workflow_runs SET end_time = stop_time')
    )
    
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_column('storage_type')
        batch_op.drop_column('stop_time')
        batch_op.drop_column('creation_time')
        batch_op.drop_column('storage_capacity')
        batch_op.drop_column('priority')
        batch_op.drop_column('workflow_id')
        batch_op.drop_column('arn')

    # ### end Alembic commands ###
