"""create tables

Revision ID: 65510080a98b
Revises: 
Create Date: 2025-04-13 11:02:15.689323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65510080a98b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('workflow_params', sa.JSON(), nullable=True),
    sa.Column('workflow_type', sa.String(length=50), nullable=False),
    sa.Column('workflow_type_version', sa.String(length=20), nullable=False),
    sa.Column('workflow_engine', sa.String(length=50), nullable=True),
    sa.Column('workflow_engine_version', sa.String(length=20), nullable=True),
    sa.Column('workflow_url', sa.String(length=500), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('task_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cmd', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('stdout', sa.String(length=500), nullable=True),
    sa.Column('stderr', sa.String(length=500), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('system_logs', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_logs')
    op.drop_table('workflow_runs')
    # ### end Alembic commands ###
